#!/usr/bin/env node

const fs = require('fs')

let file = fs.readFileSync('/tron/java-tron/src/main/java/org/tron/program/Version.java', 'utf-8')

let javaTronVersion = file.match(/"([^"]+)"/)[1]

// the version was not updated correctly in the release
if (javaTronVersion === '3.2.1.1')
  javaTronVersion = '3.2.1.2'

const versions = {
  versions: {
    "tron quickstart": require('/tron/app/package').version,
    "java-tron": javaTronVersion
  }
}

console.log(
    JSON.stringify(versions, null, 2)
)
